create extension if not exists "uuid-ossp";
create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table if not exists schools(id uuid primary key default uuid_generate_v4(),name text not null,created_at timestamptz default now(),updated_at timestamptz default now());
create table school_settings(id uuid primary key default uuid_generate_v4(),school_id uuid references schools(id),school_name text,logo_url text,address text,contact_number text,whatsapp_number text,receipt_prefix text default 'STAF',academic_session text,principal_name text,receipt_footer_note text,sms_settings jsonb default '{}'::jsonb,whatsapp_settings jsonb default '{}'::jsonb,created_at timestamptz default now(),updated_at timestamptz default now());
create table academic_sessions(id uuid primary key default uuid_generate_v4(),name text unique,start_date date,end_date date,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table user_profiles(id uuid primary key references auth.users(id),role text check (role in ('admin','staff','viewer')) default 'viewer',full_name text,created_at timestamptz default now(),updated_at timestamptz default now());
create table classes(id uuid primary key default uuid_generate_v4(),class_name text,section text default 'A',display_order int,status text default 'active',created_at timestamptz default now(),updated_at timestamptz default now());
create table students(id uuid primary key default uuid_generate_v4(),admission_no text unique,student_name text not null,father_name text,mother_name text,class_id uuid references classes(id),section text,roll_no text,gender text,dob date,mobile_no text,whatsapp_no text,address text,transport_required boolean default false,transport_route text,admission_date date,status text default 'Active',notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table fee_structures(id uuid primary key default uuid_generate_v4(),class_id uuid references classes(id),session_id uuid references academic_sessions(id),admission_fee numeric default 0,monthly_tuition_fee numeric default 0,exam_fee numeric default 0,computer_fee numeric default 0,annual_fee numeric default 0,transport_fee numeric default 0,development_fee numeric default 0,other_fee numeric default 0,fine_default numeric default 0,due_day int default 10,created_at timestamptz default now(),updated_at timestamptz default now());
create table student_fee_settings(id uuid primary key default uuid_generate_v4(),student_id uuid references students(id),session_id uuid references academic_sessions(id),custom_monthly_tuition numeric default 0,discount_amount numeric default 0,scholarship_amount numeric default 0,transport_fee numeric default 0,old_balance numeric default 0,exam_fee_override numeric default 0,computer_fee_override numeric default 0,annual_fee_override numeric default 0,fine numeric default 0,special_concession numeric default 0,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table fee_months(id uuid primary key default uuid_generate_v4(),month_name text unique,display_order int);
create table student_monthly_ledgers(id uuid primary key default uuid_generate_v4(),student_id uuid references students(id),session_id uuid references academic_sessions(id),month_id uuid references fee_months(id),expected_fee numeric default 0,discount numeric default 0,fine numeric default 0,paid_amount numeric default 0,balance_amount numeric default 0,status text default 'Pending',due_date date,remarks text,created_at timestamptz default now(),updated_at timestamptz default now());
create table payments(id uuid primary key default uuid_generate_v4(),student_id uuid references students(id),amount numeric not null,months text[],payment_mode text,transaction_id text,payment_date date,remarks text,collected_by uuid references auth.users(id),receipt_no text unique,created_at timestamptz default now(),updated_at timestamptz default now());
create table payment_items(id uuid primary key default uuid_generate_v4(),payment_id uuid references payments(id),fee_head text,amount numeric);
create table receipts(id uuid primary key default uuid_generate_v4(),payment_id uuid references payments(id),student_id uuid references students(id),receipt_no text unique,amount numeric,is_cancelled boolean default false,cancelled_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table messages(id uuid primary key default uuid_generate_v4(),student_id uuid references students(id),message_type text,channel text,content text,sent_status text default 'Draft',sent_by uuid references auth.users(id),sent_date timestamptz);
create table audit_logs(id uuid primary key default uuid_generate_v4(),action text,table_name text,record_id uuid,user_id uuid references auth.users(id),meta jsonb default '{}'::jsonb,created_at timestamptz default now());

create index on students(class_id); create index on payments(student_id); create index on receipts(payment_id); create index on student_monthly_ledgers(student_id);

do $$ declare t text; begin for t in select unnest(array['schools','school_settings','academic_sessions','user_profiles','classes','students','fee_structures','student_fee_settings','student_monthly_ledgers','payments','payment_items','receipts','messages']) loop execute format('drop trigger if exists trg_%s_updated on %s; create trigger trg_%s_updated before update on %s for each row execute function set_updated_at();',t,t,t,t); end loop; end $$;

alter table classes enable row level security; alter table students enable row level security; alter table payments enable row level security; alter table receipts enable row level security; alter table messages enable row level security; alter table fee_structures enable row level security; alter table student_fee_settings enable row level security;
create policy "authenticated read" on classes for select to authenticated using (true);
create policy "admin manage classes" on classes for all to authenticated using ((select role from user_profiles where id=auth.uid())='admin') with check ((select role from user_profiles where id=auth.uid())='admin');
create policy "students read" on students for select to authenticated using (true);
create policy "students write admin staff" on students for insert to authenticated with check ((select role from user_profiles where id=auth.uid()) in ('admin','staff'));
create policy "payments insert admin staff" on payments for insert to authenticated with check ((select role from user_profiles where id=auth.uid()) in ('admin','staff'));
create policy "payments read" on payments for select to authenticated using (true);
create policy "payments update" on payments for update to authenticated using ((select role from user_profiles where id=auth.uid()) in ('admin','staff'));
create policy "payments delete admin only" on payments for delete to authenticated using ((select role from user_profiles where id=auth.uid())='admin');
create policy "receipt cancel admin" on receipts for update to authenticated using ((select role from user_profiles where id=auth.uid())='admin');

insert into classes(class_name,section,display_order) values ('PG','A',1),('LKG','A',2),('UKG','A',3),('Class 1','A',4),('Class 2','A',5),('Class 3','A',6),('Class 4','A',7),('Class 5','A',8),('Class 6','A',9),('Class 7','A',10),('Class 8','A',11) on conflict do nothing;
insert into academic_sessions(name,start_date,end_date,is_active) values ('2026-27','2026-04-01','2027-03-31',true) on conflict do nothing;
insert into fee_months(month_name,display_order) values ('April',1),('May',2),('June',3),('July',4),('August',5),('September',6),('October',7),('November',8),('December',9),('January',10),('February',11),('March',12) on conflict do nothing;

create or replace view student_due_summary as select s.id student_id,s.student_name,s.father_name,c.class_name,s.section,sum(l.expected_fee) expected,sum(l.paid_amount) paid,sum(l.balance_amount) pending from students s left join classes c on s.class_id=c.id left join student_monthly_ledgers l on l.student_id=s.id group by s.id,c.class_name;
create or replace view class_fee_summary as select c.id class_id,c.class_name,count(distinct s.id) total_students,coalesce(sum(l.expected_fee),0) expected,coalesce(sum(l.paid_amount),0) collected,coalesce(sum(l.balance_amount),0) pending from classes c left join students s on s.class_id=c.id left join student_monthly_ledgers l on l.student_id=s.id group by c.id;
create or replace view monthly_collection_summary as select date_trunc('month', payment_date)::date as collection_month, sum(amount) as total_collection from payments group by 1 order by 1;
create or replace view pending_fee_students as select * from student_due_summary where pending>0;
create or replace view daily_collection_summary as select payment_date collection_date,sum(amount) total_collection from payments group by payment_date;
